// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"time"
)

type Delegation struct {
	ID            int64
	Address       string
	Tapscripts    []string
	RenewalWindow int64
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	MaxFee        int64
}

type Renewal struct {
	ID             int64
	DelegationID   int64
	Outpoints      []string
	CommitmentTxid string
	Success        bool
	Error          string
	AttemptedAt    time.Time
}
