// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package queries

import (
	"context"

	"github.com/lib/pq"
)

const cancelDelegation = `-- name: CancelDelegation :execrows
UPDATE delegations SET status = 'cancelled', updated_at = NOW() WHERE address = $1
`

func (q *Queries) CancelDelegation(ctx context.Context, address string) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelDelegation, address)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertRenewal = `-- name: InsertRenewal :exec
INSERT INTO renewals (delegation_id, outpoints, commitment_txid, success, error)
VALUES ($1, $2, $3, $4, $5)
`

type InsertRenewalParams struct {
	DelegationID   int64
	Outpoints      []string
	CommitmentTxid string
	Success        bool
	Error          string
}

func (q *Queries) InsertRenewal(ctx context.Context, arg InsertRenewalParams) error {
	_, err := q.db.ExecContext(ctx, insertRenewal,
		arg.DelegationID,
		pq.Array(arg.Outpoints),
		arg.CommitmentTxid,
		arg.Success,
		arg.Error,
	)
	return err
}

const selectDelegation = `-- name: SelectDelegation :one
SELECT id, address, tapscripts, renewal_window, status, created_at, updated_at FROM delegations WHERE address = $1
`

func (q *Queries) SelectDelegation(ctx context.Context, address string) (Delegation, error) {
	row := q.db.QueryRowContext(ctx, selectDelegation, address)
	var i Delegation
	err := row.Scan(
		&i.ID,
		&i.Address,
		pq.Array(&i.Tapscripts),
		&i.RenewalWindow,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectDelegations = `-- name: SelectDelegations :many
SELECT id, address, tapscripts, renewal_window, status, created_at, updated_at FROM delegations
WHERE $1::text = '' OR status = $1::text
ORDER BY created_at DESC
`

func (q *Queries) SelectDelegations(ctx context.Context, status string) ([]Delegation, error) {
	rows, err := q.db.QueryContext(ctx, selectDelegations, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delegation
	for rows.Next() {
		var i Delegation
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			pq.Array(&i.Tapscripts),
			&i.RenewalWindow,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectRenewals = `-- name: SelectRenewals :many
SELECT id, delegation_id, outpoints, commitment_txid, success, error, attempted_at FROM renewals
WHERE delegation_id = $1
ORDER BY attempted_at DESC
LIMIT $2
`

type SelectRenewalsParams struct {
	DelegationID int64
	MaxRows      int32
}

func (q *Queries) SelectRenewals(ctx context.Context, arg SelectRenewalsParams) ([]Renewal, error) {
	rows, err := q.db.QueryContext(ctx, selectRenewals, arg.DelegationID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Renewal
	for rows.Next() {
		var i Renewal
		if err := rows.Scan(
			&i.ID,
			&i.DelegationID,
			pq.Array(&i.Outpoints),
			&i.CommitmentTxid,
			&i.Success,
			&i.Error,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDelegation = `-- name: UpsertDelegation :one
INSERT INTO delegations (address, tapscripts, renewal_window)
VALUES ($1, $2, $3)
ON CONFLICT (address) DO UPDATE SET status = 'active', updated_at = NOW()
    WHERE delegations.status = 'cancelled'
RETURNING id, address, tapscripts, renewal_window, status, created_at, updated_at
`

type UpsertDelegationParams struct {
	Address       string
	Tapscripts    []string
	RenewalWindow int64
}

func (q *Queries) UpsertDelegation(ctx context.Context, arg UpsertDelegationParams) (Delegation, error) {
	row := q.db.QueryRowContext(ctx, upsertDelegation, arg.Address, pq.Array(arg.Tapscripts), arg.RenewalWindow)
	var i Delegation
	err := row.Scan(
		&i.ID,
		&i.Address,
		pq.Array(&i.Tapscripts),
		&i.RenewalWindow,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
