// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package queries

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const cancelDelegation = `-- name: CancelDelegation :execrows
UPDATE delegations SET status = $1, updated_at = NOW() WHERE address = $2
`

type CancelDelegationParams struct {
	Status  string
	Address string
}

func (q *Queries) CancelDelegation(ctx context.Context, arg CancelDelegationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelDelegation, arg.Status, arg.Address)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countActiveDelegations = `-- name: CountActiveDelegations :one
SELECT COUNT(*) FROM delegations WHERE status = 'active'
`

func (q *Queries) CountActiveDelegations(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveDelegations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRenewalsBefore = `-- name: DeleteRenewalsBefore :exec
DELETE FROM renewals r WHERE r.attempted_at < $1
    -- a failure is stored once: keep it while it is the delegation's latest state
    AND EXISTS (SELECT 1 FROM renewals newer
                WHERE newer.delegation_id = r.delegation_id AND newer.attempted_at > r.attempted_at)
`

func (q *Queries) DeleteRenewalsBefore(ctx context.Context, before time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteRenewalsBefore, before)
	return err
}

const insertRenewal = `-- name: InsertRenewal :exec
INSERT INTO renewals (delegation_id, outpoints, commitment_txid, success, error)
VALUES ($1, $2, $3, $4, $5)
`

type InsertRenewalParams struct {
	DelegationID   int64
	Outpoints      []string
	CommitmentTxid string
	Success        bool
	Error          string
}

func (q *Queries) InsertRenewal(ctx context.Context, arg InsertRenewalParams) error {
	_, err := q.db.ExecContext(ctx, insertRenewal,
		arg.DelegationID,
		pq.Array(arg.Outpoints),
		arg.CommitmentTxid,
		arg.Success,
		arg.Error,
	)
	return err
}

const selectDelegation = `-- name: SelectDelegation :one
SELECT id, address, tapscripts, renewal_window, status, created_at, updated_at, max_fee FROM delegations WHERE address = $1
`

func (q *Queries) SelectDelegation(ctx context.Context, address string) (Delegation, error) {
	row := q.db.QueryRowContext(ctx, selectDelegation, address)
	var i Delegation
	err := row.Scan(
		&i.ID,
		&i.Address,
		pq.Array(&i.Tapscripts),
		&i.RenewalWindow,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxFee,
	)
	return i, err
}

const selectDelegations = `-- name: SelectDelegations :many
SELECT id, address, tapscripts, renewal_window, status, created_at, updated_at, max_fee FROM delegations
WHERE $1::text = '' OR status = $1::text
ORDER BY created_at DESC
`

func (q *Queries) SelectDelegations(ctx context.Context, status string) ([]Delegation, error) {
	rows, err := q.db.QueryContext(ctx, selectDelegations, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delegation
	for rows.Next() {
		var i Delegation
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			pq.Array(&i.Tapscripts),
			&i.RenewalWindow,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaxFee,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectLastRenewals = `-- name: SelectLastRenewals :many
SELECT DISTINCT ON (delegation_id) id, delegation_id, outpoints, commitment_txid, success, error, attempted_at FROM renewals
ORDER BY delegation_id, attempted_at DESC
`

func (q *Queries) SelectLastRenewals(ctx context.Context) ([]Renewal, error) {
	rows, err := q.db.QueryContext(ctx, selectLastRenewals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Renewal
	for rows.Next() {
		var i Renewal
		if err := rows.Scan(
			&i.ID,
			&i.DelegationID,
			pq.Array(&i.Outpoints),
			&i.CommitmentTxid,
			&i.Success,
			&i.Error,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectRenewals = `-- name: SelectRenewals :many
SELECT id, delegation_id, outpoints, commitment_txid, success, error, attempted_at FROM renewals
WHERE delegation_id = $1
ORDER BY attempted_at DESC
LIMIT $2
`

type SelectRenewalsParams struct {
	DelegationID int64
	MaxRows      int32
}

func (q *Queries) SelectRenewals(ctx context.Context, arg SelectRenewalsParams) ([]Renewal, error) {
	rows, err := q.db.QueryContext(ctx, selectRenewals, arg.DelegationID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Renewal
	for rows.Next() {
		var i Renewal
		if err := rows.Scan(
			&i.ID,
			&i.DelegationID,
			pq.Array(&i.Outpoints),
			&i.CommitmentTxid,
			&i.Success,
			&i.Error,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDelegation = `-- name: UpsertDelegation :one
INSERT INTO delegations (address, tapscripts, renewal_window, max_fee)
VALUES ($1, $2, $3, $4)
ON CONFLICT (address) DO UPDATE SET status = 'active', updated_at = NOW()
    WHERE delegations.status <> 'active'
RETURNING id, address, tapscripts, renewal_window, status, created_at, updated_at, max_fee
`

type UpsertDelegationParams struct {
	Address       string
	Tapscripts    []string
	RenewalWindow int64
	MaxFee        int64
}

func (q *Queries) UpsertDelegation(ctx context.Context, arg UpsertDelegationParams) (Delegation, error) {
	row := q.db.QueryRowContext(ctx, upsertDelegation,
		arg.Address,
		pq.Array(arg.Tapscripts),
		arg.RenewalWindow,
		arg.MaxFee,
	)
	var i Delegation
	err := row.Scan(
		&i.ID,
		&i.Address,
		pq.Array(&i.Tapscripts),
		&i.RenewalWindow,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxFee,
	)
	return i, err
}
