// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package queries

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const artifactReferenced = `-- name: ArtifactReferenced :one
SELECT EXISTS (SELECT 1 FROM templates WHERE $1::text = ANY(artifact_ids))
`

func (q *Queries) ArtifactReferenced(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, artifactReferenced, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countActiveDelegations = `-- name: CountActiveDelegations :one
SELECT COUNT(*) FROM delegations WHERE status = 'active'
`

func (q *Queries) CountActiveDelegations(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveDelegations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDelegationsByTemplate = `-- name: CountDelegationsByTemplate :many
SELECT template_id, COUNT(*) AS n FROM delegations GROUP BY template_id
`

type CountDelegationsByTemplateRow struct {
	TemplateID string
	N          int64
}

func (q *Queries) CountDelegationsByTemplate(ctx context.Context) ([]CountDelegationsByTemplateRow, error) {
	rows, err := q.db.QueryContext(ctx, countDelegationsByTemplate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountDelegationsByTemplateRow
	for rows.Next() {
		var i CountDelegationsByTemplateRow
		if err := rows.Scan(&i.TemplateID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteArtifact = `-- name: DeleteArtifact :execrows
DELETE FROM artifacts WHERE id = $1
`

func (q *Queries) DeleteArtifact(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteArtifact, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRenewalsBefore = `-- name: DeleteRenewalsBefore :exec
DELETE FROM renewals r WHERE r.attempted_at < $1
    -- a failure is stored once: keep it while it is the delegation's latest state
    AND EXISTS (SELECT 1 FROM renewals newer
                WHERE newer.delegation_id = r.delegation_id AND newer.attempted_at > r.attempted_at)
`

func (q *Queries) DeleteRenewalsBefore(ctx context.Context, before time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteRenewalsBefore, before)
	return err
}

const deleteSettlement = `-- name: DeleteSettlement :exec
DELETE FROM settlements WHERE txid = $1 AND spent_by = $2
`

type DeleteSettlementParams struct {
	Txid    string
	SpentBy string
}

func (q *Queries) DeleteSettlement(ctx context.Context, arg DeleteSettlementParams) error {
	_, err := q.db.ExecContext(ctx, deleteSettlement, arg.Txid, arg.SpentBy)
	return err
}

const deleteTemplate = `-- name: DeleteTemplate :execrows
DELETE FROM templates WHERE id = $1
`

func (q *Queries) DeleteTemplate(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTemplate, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const expireDelegations = `-- name: ExpireDelegations :execrows
UPDATE delegations SET status = 'expired', updated_at = NOW()
WHERE status = 'active' AND expires_at IS NOT NULL AND expires_at <= $1
`

func (q *Queries) ExpireDelegations(ctx context.Context, before sql.NullTime) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireDelegations, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertDelegation = `-- name: InsertDelegation :one
WITH inserted AS (
    INSERT INTO delegations (fingerprint, address, template_id, variables, parent_id, expires_at, delegate_pubkey, slots)
    SELECT $1::text, $2::text, $3::text, $4::jsonb, $5::bigint,
        $6::timestamptz, $7::text, $8::jsonb
    WHERE $9::int = 0 OR (SELECT COUNT(*) FROM delegations WHERE status = 'active') < $9::int
    -- only active rows are unique: a stopped instance registered again is a new row
    ON CONFLICT (fingerprint) WHERE status = 'active' DO UPDATE SET fingerprint = EXCLUDED.fingerprint
    RETURNING id, fingerprint, address, template_id, variables, parent_id, expires_at, delegate_pubkey, slots, status, created_at, updated_at
)
SELECT id, fingerprint, address, template_id, variables, parent_id, expires_at, delegate_pubkey, slots, status, created_at, updated_at FROM inserted
UNION ALL (SELECT id, fingerprint, address, template_id, variables, parent_id, expires_at, delegate_pubkey, slots, status, created_at, updated_at FROM delegations WHERE fingerprint = $1 AND status = 'active')
LIMIT 1
`

type InsertDelegationParams struct {
	Fingerprint    string
	Address        string
	TemplateID     string
	Variables      json.RawMessage
	ParentID       sql.NullInt64
	ExpiresAt      sql.NullTime
	DelegatePubkey string
	Slots          json.RawMessage
	MaxActive      int32
}

type InsertDelegationRow struct {
	ID             int64
	Fingerprint    string
	Address        string
	TemplateID     string
	Variables      json.RawMessage
	ParentID       sql.NullInt64
	ExpiresAt      sql.NullTime
	DelegatePubkey string
	Slots          json.RawMessage
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// no row: max_active (0 = uncapped) active delegations exist and none has the fingerprint
func (q *Queries) InsertDelegation(ctx context.Context, arg InsertDelegationParams) (InsertDelegationRow, error) {
	row := q.db.QueryRowContext(ctx, insertDelegation,
		arg.Fingerprint,
		arg.Address,
		arg.TemplateID,
		arg.Variables,
		arg.ParentID,
		arg.ExpiresAt,
		arg.DelegatePubkey,
		arg.Slots,
		arg.MaxActive,
	)
	var i InsertDelegationRow
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.Address,
		&i.TemplateID,
		&i.Variables,
		&i.ParentID,
		&i.ExpiresAt,
		&i.DelegatePubkey,
		&i.Slots,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRenewal = `-- name: InsertRenewal :exec
INSERT INTO renewals (delegation_id, outpoints, commitment_txid, success, error)
VALUES ($1, $2, $3, $4, $5)
`

type InsertRenewalParams struct {
	DelegationID   int64
	Outpoints      []string
	CommitmentTxid string
	Success        bool
	Error          string
}

func (q *Queries) InsertRenewal(ctx context.Context, arg InsertRenewalParams) error {
	_, err := q.db.ExecContext(ctx, insertRenewal,
		arg.DelegationID,
		pq.Array(arg.Outpoints),
		arg.CommitmentTxid,
		arg.Success,
		arg.Error,
	)
	return err
}

const recordTemplateOutcome = `-- name: RecordTemplateOutcome :one
UPDATE templates
SET failures = CASE WHEN $1::boolean THEN 0 ELSE failures + 1 END,
    status = CASE WHEN NOT $1::boolean AND failures + 1 >= $2::int THEN 'disabled' ELSE status END,
    updated_at = NOW()
WHERE id = $3
RETURNING failures, status
`

type RecordTemplateOutcomeParams struct {
	Success     bool
	MaxFailures int32
	ID          string
}

type RecordTemplateOutcomeRow struct {
	Failures int32
	Status   string
}

func (q *Queries) RecordTemplateOutcome(ctx context.Context, arg RecordTemplateOutcomeParams) (RecordTemplateOutcomeRow, error) {
	row := q.db.QueryRowContext(ctx, recordTemplateOutcome, arg.Success, arg.MaxFailures, arg.ID)
	var i RecordTemplateOutcomeRow
	err := row.Scan(&i.Failures, &i.Status)
	return i, err
}

const resumeDelegation = `-- name: ResumeDelegation :execrows
UPDATE delegations SET status = 'active', updated_at = NOW() WHERE id = $1 AND status = 'cancelled'
`

func (q *Queries) ResumeDelegation(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, resumeDelegation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const selectActiveDelegationByOutpoint = `-- name: SelectActiveDelegationByOutpoint :one
SELECT id, fingerprint, address, template_id, variables, parent_id, expires_at, delegate_pubkey, slots, status, created_at, updated_at FROM delegations
WHERE status = 'active' AND slots @> jsonb_build_array(jsonb_build_object('outpoint', $1::text))
LIMIT 1
`

func (q *Queries) SelectActiveDelegationByOutpoint(ctx context.Context, outpoint string) (Delegation, error) {
	row := q.db.QueryRowContext(ctx, selectActiveDelegationByOutpoint, outpoint)
	var i Delegation
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.Address,
		&i.TemplateID,
		&i.Variables,
		&i.ParentID,
		&i.ExpiresAt,
		&i.DelegatePubkey,
		&i.Slots,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectArtifact = `-- name: SelectArtifact :one
SELECT id, document, created_at FROM artifacts WHERE id = $1
`

func (q *Queries) SelectArtifact(ctx context.Context, id string) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, selectArtifact, id)
	var i Artifact
	err := row.Scan(&i.ID, &i.Document, &i.CreatedAt)
	return i, err
}

const selectArtifactSummaries = `-- name: SelectArtifactSummaries :many
SELECT id, created_at FROM artifacts ORDER BY created_at DESC
`

type SelectArtifactSummariesRow struct {
	ID        string
	CreatedAt time.Time
}

func (q *Queries) SelectArtifactSummaries(ctx context.Context) ([]SelectArtifactSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, selectArtifactSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectArtifactSummariesRow
	for rows.Next() {
		var i SelectArtifactSummariesRow
		if err := rows.Scan(&i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectDelegation = `-- name: SelectDelegation :one
SELECT id, fingerprint, address, template_id, variables, parent_id, expires_at, delegate_pubkey, slots, status, created_at, updated_at FROM delegations WHERE address = $1
ORDER BY (status = 'active') DESC, created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) SelectDelegation(ctx context.Context, address string) (Delegation, error) {
	row := q.db.QueryRowContext(ctx, selectDelegation, address)
	var i Delegation
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.Address,
		&i.TemplateID,
		&i.Variables,
		&i.ParentID,
		&i.ExpiresAt,
		&i.DelegatePubkey,
		&i.Slots,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectDelegationByID = `-- name: SelectDelegationByID :one
SELECT id, fingerprint, address, template_id, variables, parent_id, expires_at, delegate_pubkey, slots, status, created_at, updated_at FROM delegations WHERE id = $1
`

func (q *Queries) SelectDelegationByID(ctx context.Context, id int64) (Delegation, error) {
	row := q.db.QueryRowContext(ctx, selectDelegationByID, id)
	var i Delegation
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.Address,
		&i.TemplateID,
		&i.Variables,
		&i.ParentID,
		&i.ExpiresAt,
		&i.DelegatePubkey,
		&i.Slots,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectDelegationPage = `-- name: SelectDelegationPage :many
SELECT id, fingerprint, address, template_id, variables, parent_id, expires_at, delegate_pubkey, slots, status, created_at, updated_at FROM delegations
WHERE ($1::text = '' OR status = $1::text)
    AND ($2::bigint = 0 OR id < $2::bigint)
ORDER BY id DESC
LIMIT $3
`

type SelectDelegationPageParams struct {
	Status  string
	Cursor  int64
	MaxRows int32
}

func (q *Queries) SelectDelegationPage(ctx context.Context, arg SelectDelegationPageParams) ([]Delegation, error) {
	rows, err := q.db.QueryContext(ctx, selectDelegationPage, arg.Status, arg.Cursor, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delegation
	for rows.Next() {
		var i Delegation
		if err := rows.Scan(
			&i.ID,
			&i.Fingerprint,
			&i.Address,
			&i.TemplateID,
			&i.Variables,
			&i.ParentID,
			&i.ExpiresAt,
			&i.DelegatePubkey,
			&i.Slots,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectDelegations = `-- name: SelectDelegations :many
SELECT id, fingerprint, address, template_id, variables, parent_id, expires_at, delegate_pubkey, slots, status, created_at, updated_at FROM delegations
WHERE $1::text = '' OR status = $1::text
ORDER BY created_at DESC, id DESC
`

func (q *Queries) SelectDelegations(ctx context.Context, status string) ([]Delegation, error) {
	rows, err := q.db.QueryContext(ctx, selectDelegations, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delegation
	for rows.Next() {
		var i Delegation
		if err := rows.Scan(
			&i.ID,
			&i.Fingerprint,
			&i.Address,
			&i.TemplateID,
			&i.Variables,
			&i.ParentID,
			&i.ExpiresAt,
			&i.DelegatePubkey,
			&i.Slots,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectLastRenewals = `-- name: SelectLastRenewals :many
SELECT DISTINCT ON (delegation_id) id, delegation_id, outpoints, commitment_txid, success, error, attempted_at FROM renewals
ORDER BY delegation_id, attempted_at DESC
`

func (q *Queries) SelectLastRenewals(ctx context.Context) ([]Renewal, error) {
	rows, err := q.db.QueryContext(ctx, selectLastRenewals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Renewal
	for rows.Next() {
		var i Renewal
		if err := rows.Scan(
			&i.ID,
			&i.DelegationID,
			pq.Array(&i.Outpoints),
			&i.CommitmentTxid,
			&i.Success,
			&i.Error,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectLatestDelegationByFingerprint = `-- name: SelectLatestDelegationByFingerprint :one
SELECT id, fingerprint, address, template_id, variables, parent_id, expires_at, delegate_pubkey, slots, status, created_at, updated_at FROM delegations WHERE fingerprint = $1 ORDER BY id DESC LIMIT 1
`

func (q *Queries) SelectLatestDelegationByFingerprint(ctx context.Context, fingerprint string) (Delegation, error) {
	row := q.db.QueryRowContext(ctx, selectLatestDelegationByFingerprint, fingerprint)
	var i Delegation
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.Address,
		&i.TemplateID,
		&i.Variables,
		&i.ParentID,
		&i.ExpiresAt,
		&i.DelegatePubkey,
		&i.Slots,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectRenewals = `-- name: SelectRenewals :many
SELECT id, delegation_id, outpoints, commitment_txid, success, error, attempted_at FROM renewals
WHERE delegation_id = $1
ORDER BY attempted_at DESC
LIMIT $2
`

type SelectRenewalsParams struct {
	DelegationID int64
	MaxRows      int32
}

func (q *Queries) SelectRenewals(ctx context.Context, arg SelectRenewalsParams) ([]Renewal, error) {
	rows, err := q.db.QueryContext(ctx, selectRenewals, arg.DelegationID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Renewal
	for rows.Next() {
		var i Renewal
		if err := rows.Scan(
			&i.ID,
			&i.DelegationID,
			pq.Array(&i.Outpoints),
			&i.CommitmentTxid,
			&i.Success,
			&i.Error,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectSettlements = `-- name: SelectSettlements :many
SELECT txid, spent_by, delegation_id, tx, outpoints, sources, coins, checkpoints, finals, landed, created_at FROM settlements ORDER BY created_at
`

func (q *Queries) SelectSettlements(ctx context.Context) ([]Settlement, error) {
	rows, err := q.db.QueryContext(ctx, selectSettlements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Settlement
	for rows.Next() {
		var i Settlement
		if err := rows.Scan(
			&i.Txid,
			&i.SpentBy,
			&i.DelegationID,
			&i.Tx,
			&i.Outpoints,
			pq.Array(&i.Sources),
			pq.Array(&i.Coins),
			pq.Array(&i.Checkpoints),
			pq.Array(&i.Finals),
			&i.Landed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectTemplate = `-- name: SelectTemplate :one
SELECT id, document, artifact_ids, params, status, failures, trusted, created_at, updated_at FROM templates WHERE id = $1
`

func (q *Queries) SelectTemplate(ctx context.Context, id string) (Template, error) {
	row := q.db.QueryRowContext(ctx, selectTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Document,
		pq.Array(&i.ArtifactIds),
		&i.Params,
		&i.Status,
		&i.Failures,
		&i.Trusted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectTemplateSummaries = `-- name: SelectTemplateSummaries :many
SELECT id, artifact_ids, params, status, failures, trusted, created_at FROM templates
WHERE $1::text = '' OR status = $1::text
ORDER BY created_at DESC
`

type SelectTemplateSummariesRow struct {
	ID          string
	ArtifactIds []string
	Params      json.RawMessage
	Status      string
	Failures    int32
	Trusted     bool
	CreatedAt   time.Time
}

func (q *Queries) SelectTemplateSummaries(ctx context.Context, status string) ([]SelectTemplateSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, selectTemplateSummaries, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectTemplateSummariesRow
	for rows.Next() {
		var i SelectTemplateSummariesRow
		if err := rows.Scan(
			&i.ID,
			pq.Array(&i.ArtifactIds),
			&i.Params,
			&i.Status,
			&i.Failures,
			&i.Trusted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDelegationStatus = `-- name: SetDelegationStatus :execrows
UPDATE delegations SET status = $1, updated_at = NOW() WHERE id = $2 AND status = 'active'
`

type SetDelegationStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) SetDelegationStatus(ctx context.Context, arg SetDelegationStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setDelegationStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTemplateStatus = `-- name: SetTemplateStatus :execrows
UPDATE templates
SET status = $1,
    failures = CASE WHEN $1 = 'active' THEN 0 ELSE failures END,
    updated_at = NOW()
WHERE id = $2
`

type SetTemplateStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) SetTemplateStatus(ctx context.Context, arg SetTemplateStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTemplateStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTemplateTrusted = `-- name: SetTemplateTrusted :execrows
UPDATE templates SET trusted = $1, updated_at = NOW() WHERE id = $2
`

type SetTemplateTrustedParams struct {
	Trusted bool
	ID      string
}

func (q *Queries) SetTemplateTrusted(ctx context.Context, arg SetTemplateTrustedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTemplateTrusted, arg.Trusted, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const templateReferenced = `-- name: TemplateReferenced :one
SELECT EXISTS (SELECT 1 FROM delegations WHERE template_id = $1)
`

func (q *Queries) TemplateReferenced(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, templateReferenced, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertArtifact = `-- name: UpsertArtifact :one
WITH inserted AS (
    INSERT INTO artifacts (id, document)
    SELECT $1::text, $2::bytea
    WHERE $3::int = 0 OR (SELECT COUNT(*) FROM artifacts) < $3::int
    ON CONFLICT (id) DO UPDATE SET id = artifacts.id
    RETURNING id, document, created_at
)
SELECT id, document, created_at FROM inserted UNION ALL (SELECT id, document, created_at FROM artifacts WHERE id = $1) LIMIT 1
`

type UpsertArtifactParams struct {
	ID       string
	Document []byte
	MaxCount int32
}

type UpsertArtifactRow struct {
	ID        string
	Document  []byte
	CreatedAt time.Time
}

// no row: max_count (0 = uncapped) artifacts exist and none has the id
func (q *Queries) UpsertArtifact(ctx context.Context, arg UpsertArtifactParams) (UpsertArtifactRow, error) {
	row := q.db.QueryRowContext(ctx, upsertArtifact, arg.ID, arg.Document, arg.MaxCount)
	var i UpsertArtifactRow
	err := row.Scan(&i.ID, &i.Document, &i.CreatedAt)
	return i, err
}

const upsertSettlement = `-- name: UpsertSettlement :exec
INSERT INTO settlements (txid, spent_by, delegation_id, tx, outpoints, sources, coins, checkpoints, finals, landed)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (txid, spent_by) DO UPDATE SET finals = EXCLUDED.finals, landed = EXCLUDED.landed
`

type UpsertSettlementParams struct {
	Txid         string
	SpentBy      string
	DelegationID int64
	Tx           []byte
	Outpoints    json.RawMessage
	Sources      [][]byte
	Coins        []string
	Checkpoints  []string
	Finals       []string
	Landed       bool
}

func (q *Queries) UpsertSettlement(ctx context.Context, arg UpsertSettlementParams) error {
	_, err := q.db.ExecContext(ctx, upsertSettlement,
		arg.Txid,
		arg.SpentBy,
		arg.DelegationID,
		arg.Tx,
		arg.Outpoints,
		pq.Array(arg.Sources),
		pq.Array(arg.Coins),
		pq.Array(arg.Checkpoints),
		pq.Array(arg.Finals),
		arg.Landed,
	)
	return err
}

const upsertTemplate = `-- name: UpsertTemplate :one
WITH inserted AS (
    INSERT INTO templates (id, document, artifact_ids, params)
    SELECT $1::text, $2::bytea, $3::text[], $4::jsonb
    WHERE $5::int = 0 OR (SELECT COUNT(*) FROM templates) < $5::int
    ON CONFLICT (id) DO UPDATE SET id = templates.id
    RETURNING id, document, artifact_ids, params, status, failures, trusted, created_at, updated_at
)
SELECT id, document, artifact_ids, params, status, failures, trusted, created_at, updated_at FROM inserted UNION ALL (SELECT id, document, artifact_ids, params, status, failures, trusted, created_at, updated_at FROM templates WHERE id = $1) LIMIT 1
`

type UpsertTemplateParams struct {
	ID          string
	Document    []byte
	ArtifactIds []string
	Params      json.RawMessage
	MaxCount    int32
}

type UpsertTemplateRow struct {
	ID          string
	Document    []byte
	ArtifactIds []string
	Params      json.RawMessage
	Status      string
	Failures    int32
	Trusted     bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// no row: max_count (0 = uncapped) templates exist and none has the id
func (q *Queries) UpsertTemplate(ctx context.Context, arg UpsertTemplateParams) (UpsertTemplateRow, error) {
	row := q.db.QueryRowContext(ctx, upsertTemplate,
		arg.ID,
		arg.Document,
		pq.Array(arg.ArtifactIds),
		arg.Params,
		arg.MaxCount,
	)
	var i UpsertTemplateRow
	err := row.Scan(
		&i.ID,
		&i.Document,
		pq.Array(&i.ArtifactIds),
		&i.Params,
		&i.Status,
		&i.Failures,
		&i.Trusted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
